# Generated by Django 4.1.3 on 2024-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0002_alter_profile_address_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='faq.png', null=True, upload_to='profile_images'),
        ),
    ]
