# Generated by Django 4.1.3 on 2024-01-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmediaapp', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='faq.png', upload_to='profile_images'),
        ),
    ]
